apiVersion: v1
data:
  quarkus.datasource.driver: b3JnLnBvc3RncmVzcWwuRHJpdmVy
  quarkus.datasource.password: aW52ZW50b3J5
  quarkus.datasource.url: amRiYzpwb3N0Z3Jlc3FsOi8vaW52ZW50b3J5LWRhdGFiYXNlOjU0MzIvaW52ZW50b3J5
  quarkus.datasource.username: aW52ZW50b3J5
kind: Secret
metadata:
  name: inventory
type: Opaque
