apiVersion: v1
data:
  database-name: aW52ZW50b3J5
  database-password: aW52ZW50b3J5
  database-user: aW52ZW50b3J5
kind: Secret
metadata:
  labels:
    app: postgresql-persistent
    app.kubernetes.io/component: postgresql-persistent
    app.kubernetes.io/instance: postgresql-persistent
  name: inventory-database
type: Opaque
