apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-database
    app.kubernetes.io/component: order-database
    app.kubernetes.io/instance: order-database
    app.kubernetes.io/part-of: order
    app.openshift.io/runtime: mongodb
  name: order-database
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: order-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: order-database
    spec:
      containers:
      - image: docker.io/mongo:4.4.3
        imagePullPolicy: IfNotPresent
        name: order-database
        ports:
        - containerPort: 27017
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/configdb
          name: order-database-volume-1
        - mountPath: /data/db
          name: order-database-volume-2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: order-database-volume-1
      - name: order-database-volume-2
        persistentVolumeClaim:
          claimName: order-database
