apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-database
    app.kubernetes.io/component: order-database
    app.kubernetes.io/instance: order-database
  name: order-database
spec:
  ports:
  - name: 27017-tcp
    port: 27017
  selector:
    deployment: order-database
