apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: catalog:latest
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-11:1.3
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
