apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{ include "inventory-database.appLabels" . | nindent 4 }}
  name: {{ include "inventory-database.name" . | nindent 2 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.requests.size | quote | default "1Gi" }}
  storageClassName: standard