apiVersion: v1
data:
  database-name: {{ required "you must include dbCredentials.name value" .Values.dbCredentials.name }}
  database-password: {{ required "you must include dbCredentials.password value" .Values.dbCredentials.password }}
  database-user: {{ required "you must include dbCredentials.user value" .Values.dbCredentials.user}}
kind: Secret
metadata:
  labels:
    {{ include "inventory-database.appLabels" . | nindent 4 }}
  name: {{ include "inventory-database.name" . | nindent 2 }}
type: Opaque