apiVersion: v1
kind: Service
metadata:
  labels:
    app: datagrid-service
    app.kubernetes.io/component: datagrid-service
    app.kubernetes.io/instance: datagrid-service
    app.kubernetes.io/part-of: cart
    app.openshift.io/runtime: datagrid
  name: datagrid-service
spec:
  ports:
  - name: 7600-tcp
    port: 7600
  - name: 8080-tcp
    port: 8080
  - name: 8181-tcp
    port: 8181
  - name: 8888-tcp
    port: 8888
  - name: 9990-tcp
    port: 9990
  - name: 11211-tcp
    port: 11211
  - name: 11222-tcp
    port: 11222
  - name: 57600-tcp
    port: 57600
  selector:
    app.kubernetes.io/part-of: cart
    app.openshift.io/runtime: datagrid
    deployment: datagrid-service
