apiVersion: v1
data:
  database-name: Y2F0YWxvZw==
  database-password: Y2F0YWxvZw==
  database-user: Y2F0YWxvZw==
kind: Secret
metadata:
  labels:
    app: postgresql-persistent
    app.kubernetes.io/component: postgresql-persistent
    app.kubernetes.io/instance: postgresql-persistent
  name: catalog-database
type: Opaque
