apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-persistent
    app.kubernetes.io/component: postgresql-persistent
    app.kubernetes.io/instance: postgresql-persistent
  name: catalog-database
spec:
  clusterIP: 172.30.207.202
  ports:
  - name: postgresql
    port: 5432
  selector:
    name: catalog-database
