apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    {{ include "inventory.bcLabels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: inventory:latest
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-11:1.3
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5