apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{ include "inventory.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  port:
    targetPort: "{{ .Values.service.port1 }}-tcp"
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  wildcardPolicy: None