apiVersion: v1
data:
  quarkus.datasource.driver: {{ .Values.quarkusSecret.driver }}
  quarkus.datasource.password: {{ .Values.quarkusSecret.password }}
  quarkus.datasource.url: {{ .Values.quarkusSecret.url }}
  quarkus.datasource.username: {{ .Values.quarkusSecret.username }}
kind: Secret
metadata:
  name: inventory
type: Opaque