apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "inventory.labels" . | nindent 4 }}
  name: {{ include "inventory.fullname" . }}
spec:
  ports:
  - name: "{{ .Values.service.port1 }}-tcp"
    port: {{ .Values.service.port1 }}
  - name: "{{ .Values.service.port2 }}-tcp"
    port: {{ .Values.service.port2 }}
  - name: "{{ .Values.service.port3 }}-tcp"
    port: {{ .Values.service.port3 }}
  selector:
    {{ include "inventory.selectorLabels" . | nindent 4 }}